import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Scale, Users, Clock, CheckCircle, XCircle, TrendingUp, Eye, Download, RefreshCw, BarChart2, FileText, AlertTriangle } from 'lucide-react';
import { ethicalAPI } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { toast } from 'react-toastify';

const AdminEthicalCommitteeDashboard = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [cases, setCases] = useState([]);
  const [appeals, setAppeals] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.role !== 'ADMIN') {
      navigate('/ethical');
      return;
    }
    loadData();
  }, [user, navigate]);

  const loadData = async () => {
    setLoading(true);
    try {
      const [casesRes, appealsRes] = await Promise.all([
        ethicalAPI.getCases(),
        ethicalAPI.getAppeals(),
      ]);
      setCases(casesRes.data);
      setAppeals(appealsRes.data);
    } catch {
      toast.error('Failed to load dashboard data');
    } finally {
      setLoading(false);
    }
  };

  const stats = {
    totalCases: cases.length,
    pendingCases: cases.filter(c => c.status === 'PENDING').length,
    underReview: cases.filter(c => c.status === 'UNDER_REVIEW').length,
    approvedCases: cases.filter(c => c.status === 'APPROVED').length,
    rejectedCases: cases.filter(c => c.status === 'REJECTED').length,
    totalAppeals: appeals.length,
    pendingAppeals: appeals.filter(a => a.status === 'PENDING').length,
    resolutionRate: cases.length > 0
      ? (((cases.filter(c => c.status === 'APPROVED' || c.status === 'REJECTED').length) / cases.length) * 100).toFixed(1)
      : '0.0',
  };

  const recentCases = [...cases].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 5);
  const urgentCases = cases.filter(c => c.status === 'PENDING').slice(0, 5);

  const statusColor = (s) => {
    const m = { PENDING: 'var(--amber)', UNDER_REVIEW: 'var(--blue)', APPROVED: 'var(--green)', REJECTED: 'var(--red)' };
    return m[s] || 'var(--text-muted)';
  };

  const generateFullReport = () => {
    const now = new Date().toLocaleString();
    const report = `ETHICAL REVIEW COMMITTEE - ADMINISTRATIVE REPORT
Generated: ${now}
Generated By: ${user?.name}
=================================================

EXECUTIVE SUMMARY
-----------------
Total Cases: ${stats.totalCases}
Active Cases (Pending): ${stats.pendingCases}
Under Review: ${stats.underReview}
Approved: ${stats.approvedCases}
Rejected: ${stats.rejectedCases}
Total Appeals: ${stats.totalAppeals}
Pending Appeals: ${stats.pendingAppeals}
Resolution Rate: ${stats.resolutionRate}%

CASE TYPE BREAKDOWN
-------------------
${['GRADE_APPEAL', 'DISCIPLINARY_APPEAL', 'ETHICAL_CONCERN', 'ACADEMIC_MISCONDUCT', 'OTHER'].map(type => {
  const count = cases.filter(c => c.type === type).length;
  return `${type.replace(/_/g, ' ')}: ${count}`;
}).join('\n')}

URGENT PENDING CASES (Requires Action)
---------------------------------------
${urgentCases.map((c, i) => `${i + 1}. ${c.title} | ${c.submittedByName} | ${new Date(c.createdAt).toLocaleDateString()}`).join('\n') || 'None'}

RECENT ACTIVITY (Last 5 Cases)
--------------------------------
${recentCases.map((c, i) => `${i + 1}. [${c.status}] ${c.title} - ${c.submittedByName} - ${new Date(c.createdAt).toLocaleDateString()}`).join('\n')}

END OF REPORT`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `ethical-admin-report-${Date.now()}.txt`; a.click();
    URL.revokeObjectURL(url);
    toast.success('Admin report generated');
  };

  if (loading) return (
    <div className="flex justify-center py-12">
      <div className="animate-spin w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full" />
    </div>
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>Ethics Committee Dashboard</h1>
          <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Administrative overview of all ethical review activities</p>
        </div>
        <div className="flex gap-2">
          <button onClick={loadData} className="btn-secondary flex items-center gap-2">
            <RefreshCw size={14} /> Refresh
          </button>
          <button onClick={generateFullReport} className="btn-primary flex items-center gap-2">
            <Download size={14} /> Generate Report
          </button>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Total Cases', value: stats.totalCases, icon: Scale, color: 'var(--indigo)', sub: 'All time' },
          { label: 'Pending Action', value: stats.pendingCases, icon: Clock, color: 'var(--amber)', sub: 'Requires review' },
          { label: 'Under Review', value: stats.underReview, icon: Eye, color: 'var(--blue)', sub: 'In progress' },
          { label: 'Resolution Rate', value: `${stats.resolutionRate}%`, icon: TrendingUp, color: 'var(--green)', sub: 'Resolved cases' },
        ].map((s, i) => (
          <div key={i} className="card" style={{ padding: '1.25rem' }}>
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>{s.label}</p>
              <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: `${s.color}18` }}>
                <s.icon size={14} style={{ color: s.color }} />
              </div>
            </div>
            <p className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>{s.value}</p>
            <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>{s.sub}</p>
          </div>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { label: 'Review Cases', path: '/ethical', icon: Scale, color: 'var(--indigo)', count: stats.pendingCases },
          { label: 'Appeal Review', path: '/ethical/appeal-review', icon: FileText, color: 'var(--blue)', count: stats.pendingAppeals },
          { label: 'Case History', path: '/ethical/history', icon: BarChart2, color: 'var(--cyan)', count: stats.totalCases },
          { label: 'Create Case', path: '/ethical/create', icon: AlertTriangle, color: 'var(--amber)', count: null },
        ].map((action, i) => (
          <Link key={i} to={action.path} className="card hover:border-blue-500/30 transition-all flex items-center gap-3" style={{ padding: '1rem', textDecoration: 'none' }}>
            <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{ background: `${action.color}18` }}>
              <action.icon size={16} style={{ color: action.color }} />
            </div>
            <div>
              <p className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>{action.label}</p>
              {action.count !== null && (
                <p className="text-xs" style={{ color: 'var(--text-muted)' }}>{action.count} items</p>
              )}
            </div>
          </Link>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Urgent Cases */}
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-bold flex items-center gap-2" style={{ color: 'var(--text-primary)' }}>
              <Clock size={14} style={{ color: 'var(--amber)' }} /> Urgent — Pending Review
            </h3>
            <span className="text-xs px-2 py-0.5 rounded-full font-bold" style={{ background: 'rgba(245,158,11,0.15)', color: 'var(--amber)' }}>
              {stats.pendingCases} pending
            </span>
          </div>
          {urgentCases.length === 0 ? (
            <p className="text-sm text-center py-4" style={{ color: 'var(--text-muted)' }}>No pending cases ✓</p>
          ) : (
            <div className="space-y-2">
              {urgentCases.map(c => (
                <Link key={c.id} to={`/ethical/case/${c.id}`}
                  className="flex items-center justify-between p-3 rounded-lg hover:bg-white/3 transition-colors"
                  style={{ border: '1px solid var(--border-subtle)', textDecoration: 'none' }}
                >
                  <div>
                    <p className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>{c.title}</p>
                    <p className="text-xs" style={{ color: 'var(--text-muted)' }}>{c.submittedByName} · {new Date(c.createdAt).toLocaleDateString()}</p>
                  </div>
                  <Eye size={14} style={{ color: 'var(--blue)' }} />
                </Link>
              ))}
            </div>
          )}
        </div>

        {/* Recent Activity */}
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>Recent Cases</h3>
            <Link to="/ethical/history" className="text-xs" style={{ color: 'var(--blue)', textDecoration: 'none' }}>View All</Link>
          </div>
          {recentCases.length === 0 ? (
            <p className="text-sm text-center py-4" style={{ color: 'var(--text-muted)' }}>No cases yet</p>
          ) : (
            <div className="space-y-2">
              {recentCases.map(c => (
                <Link key={c.id} to={`/ethical/case/${c.id}`}
                  className="flex items-center justify-between p-3 rounded-lg hover:bg-white/3 transition-colors"
                  style={{ border: '1px solid var(--border-subtle)', textDecoration: 'none' }}
                >
                  <div>
                    <p className="text-sm font-bold" style={{ color: 'var(--text-primary)' }}>{c.title}</p>
                    <p className="text-xs" style={{ color: 'var(--text-muted)' }}>{c.type?.replace(/_/g, ' ')} · {new Date(c.createdAt).toLocaleDateString()}</p>
                  </div>
                  <span className="text-xs px-2 py-0.5 rounded-full font-bold" style={{
                    background: `${statusColor(c.status)}18`,
                    color: statusColor(c.status),
                  }}>
                    {c.status}
                  </span>
                </Link>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Decision Breakdown */}
      <div className="card">
        <h3 className="text-sm font-bold mb-4" style={{ color: 'var(--text-primary)' }}>Decision Breakdown</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'Approved', value: stats.approvedCases, color: 'var(--green)', pct: stats.totalCases > 0 ? ((stats.approvedCases / stats.totalCases) * 100).toFixed(0) : 0 },
            { label: 'Rejected', value: stats.rejectedCases, color: 'var(--red)', pct: stats.totalCases > 0 ? ((stats.rejectedCases / stats.totalCases) * 100).toFixed(0) : 0 },
            { label: 'Under Review', value: stats.underReview, color: 'var(--blue)', pct: stats.totalCases > 0 ? ((stats.underReview / stats.totalCases) * 100).toFixed(0) : 0 },
            { label: 'Pending', value: stats.pendingCases, color: 'var(--amber)', pct: stats.totalCases > 0 ? ((stats.pendingCases / stats.totalCases) * 100).toFixed(0) : 0 },
          ].map((d, i) => (
            <div key={i}>
              <div className="flex items-center justify-between mb-1">
                <p className="text-xs" style={{ color: 'var(--text-muted)' }}>{d.label}</p>
                <p className="text-xs font-bold" style={{ color: d.color }}>{d.value}</p>
              </div>
              <div className="w-full rounded-full h-2" style={{ background: 'rgba(255,255,255,0.06)' }}>
                <div className="h-2 rounded-full transition-all" style={{ width: `${d.pct}%`, background: d.color }} />
              </div>
              <p className="text-xs mt-1" style={{ color: 'var(--text-muted)' }}>{d.pct}%</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default AdminEthicalCommitteeDashboard;
