import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Scale, Search, Download, Eye, Filter, History, TrendingUp, CheckCircle, XCircle, Clock } from 'lucide-react';
import { ethicalAPI } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { toast } from 'react-toastify';

const CaseHistoryPage = () => {
  const { user } = useAuth();
  const [cases, setCases] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [typeFilter, setTypeFilter] = useState('ALL');
  const [dateSort, setDateSort] = useState('DESC');

  useEffect(() => {
    ethicalAPI.getCases()
      .then(res => setCases(res.data))
      .catch(() => toast.error('Failed to load case history'))
      .finally(() => setLoading(false));
  }, []);

  const statusColor = (s) => {
    const m = { PENDING: '#f59e0b', UNDER_REVIEW: '#3b82f6', APPROVED: '#10b981', REJECTED: '#ef4444', CLOSED: '#6366f1' };
    return m[s] || '#8ba3cc';
  };

  const types = ['ALL', ...new Set(cases.map(c => c.type).filter(Boolean))];
  const statuses = ['ALL', 'PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED'];

  const filtered = cases
    .filter(c => {
      const matchSearch = c.title?.toLowerCase().includes(search.toLowerCase()) ||
        c.submittedByName?.toLowerCase().includes(search.toLowerCase()) ||
        c.description?.toLowerCase().includes(search.toLowerCase());
      const matchStatus = statusFilter === 'ALL' || c.status === statusFilter;
      const matchType = typeFilter === 'ALL' || c.type === typeFilter;
      return matchSearch && matchStatus && matchType;
    })
    .sort((a, b) => dateSort === 'DESC'
      ? new Date(b.createdAt) - new Date(a.createdAt)
      : new Date(a.createdAt) - new Date(b.createdAt)
    );

  const stats = {
    total: cases.length,
    pending: cases.filter(c => c.status === 'PENDING').length,
    approved: cases.filter(c => c.status === 'APPROVED').length,
    rejected: cases.filter(c => c.status === 'REJECTED').length,
  };

  const exportCSV = () => {
    const headers = ['ID', 'Title', 'Type', 'Status', 'Submitted By', 'Decision', 'Date'];
    const rows = filtered.map(c => [
      c.id, c.title, c.type, c.status, c.submittedByName, c.decision || '', new Date(c.createdAt).toLocaleDateString()
    ]);
    const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `ethical-case-history-${Date.now()}.csv`; a.click();
    URL.revokeObjectURL(url);
    toast.success('Case history exported');
  };

  const generateReport = () => {
    const reportDate = new Date().toLocaleDateString();
    const report = `ETHICAL REVIEW & APPEALS - CASE HISTORY REPORT
Generated: ${reportDate}
Generated By: ${user?.name || 'System'}
==============================================

SUMMARY
-------
Total Cases: ${stats.total}
Pending: ${stats.pending}
Approved: ${stats.approved}
Rejected: ${stats.rejected}
Resolution Rate: ${stats.total > 0 ? (((stats.approved + stats.rejected) / stats.total) * 100).toFixed(1) : 0}%

CASE DETAILS
------------
${filtered.map((c, i) => `
${i + 1}. ${c.title}
   ID: ${c.id}
   Type: ${c.type?.replace(/_/g, ' ')}
   Status: ${c.status}
   Submitted By: ${c.submittedByName}
   Date: ${new Date(c.createdAt).toLocaleDateString()}
   Decision: ${c.decision || 'Pending'}
   ${c.reason ? `Reason: ${c.reason}` : ''}
`).join('')}

END OF REPORT`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `ethical-report-${Date.now()}.txt`; a.click();
    URL.revokeObjectURL(url);
    toast.success('Report generated and downloaded');
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>Case History</h1>
          <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Complete history of all ethical review cases and appeals</p>
        </div>
        <div className="flex gap-2">
          <button onClick={exportCSV} className="btn-secondary flex items-center gap-2">
            <Download size={14} /> Export CSV
          </button>
          <button onClick={generateReport} className="btn-primary flex items-center gap-2">
            <TrendingUp size={14} /> Generate Report
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Total Cases', value: stats.total, icon: History, color: 'var(--blue)' },
          { label: 'Pending', value: stats.pending, icon: Clock, color: 'var(--amber)' },
          { label: 'Approved', value: stats.approved, icon: CheckCircle, color: 'var(--green)' },
          { label: 'Rejected', value: stats.rejected, icon: XCircle, color: 'var(--red)' },
        ].map((s, i) => (
          <div key={i} className="card" style={{ padding: '1rem' }}>
            <div className="flex items-center gap-2 mb-1">
              <s.icon size={14} style={{ color: s.color }} />
              <p className="text-xs" style={{ color: 'var(--text-muted)' }}>{s.label}</p>
            </div>
            <p className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div className="card" style={{ padding: '1rem' }}>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
          <div className="relative md:col-span-2">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: 'var(--text-muted)' }} />
            <input type="text" placeholder="Search cases..." value={search} onChange={e => setSearch(e.target.value)} className="form-input pl-9 w-full" />
          </div>
          <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="form-input">
            {statuses.map(s => <option key={s} value={s}>{s === 'ALL' ? 'All Statuses' : s.replace(/_/g, ' ')}</option>)}
          </select>
          <select value={dateSort} onChange={e => setDateSort(e.target.value)} className="form-input">
            <option value="DESC">Newest First</option>
            <option value="ASC">Oldest First</option>
          </select>
        </div>
      </div>

      {/* Cases List */}
      {loading ? (
        <div className="flex justify-center py-12">
          <div className="animate-spin w-8 h-8 border-4 border-blue-500 border-t-transparent rounded-full" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="card text-center py-12">
          <History size={40} className="mx-auto mb-3" style={{ color: 'var(--text-muted)' }} />
          <p style={{ color: 'var(--text-muted)' }}>No cases match your search criteria.</p>
        </div>
      ) : (
        <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
          <div className="px-4 py-3" style={{ borderBottom: '1px solid var(--border-subtle)' }}>
            <p className="text-xs font-bold" style={{ color: 'var(--text-muted)' }}>
              Showing {filtered.length} of {cases.length} cases
            </p>
          </div>
          <div className="divide-y" style={{ borderColor: 'var(--border-subtle)' }}>
            {filtered.map(c => (
              <div key={c.id} className="px-4 py-3 hover:bg-white/2 transition-colors">
                <div className="flex items-center justify-between">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-0.5">
                      <p className="text-sm font-bold truncate" style={{ color: 'var(--text-primary)' }}>{c.title}</p>
                      <span className="px-2 py-0.5 rounded-full text-xs font-bold shrink-0" style={{
                        background: `${statusColor(c.status)}18`,
                        color: statusColor(c.status),
                        border: `1px solid ${statusColor(c.status)}33`
                      }}>
                        {c.status}
                      </span>
                    </div>
                    <div className="flex items-center gap-4 text-xs" style={{ color: 'var(--text-muted)' }}>
                      <span>{c.submittedByName}</span>
                      <span>{c.type?.replace(/_/g, ' ')}</span>
                      <span>{new Date(c.createdAt).toLocaleDateString()}</span>
                      {c.decision && <span className="font-bold" style={{ color: c.decision === 'APPROVED' ? 'var(--green)' : 'var(--red)' }}>→ {c.decision}</span>}
                    </div>
                  </div>
                  <Link to={`/ethical/case/${c.id}`} className="ml-3 p-2 rounded-lg hover:bg-white/5 transition-colors" style={{ color: 'var(--blue)' }}>
                    <Eye size={14} />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default CaseHistoryPage;
